language: node_js
node_js:
- node
install:
  - yarn install
before_script:
  - yarn package-install
before_deploy:
  - yarn pages-build
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: gh-pages
    verbose: true
